spring:
  redis:
    host: 127.0.0.1  # Redis服务器地址
    port: 6379          # Redis服务器连接端口
    password: 123456
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500  # 连接池中的最大空闲连接
        min-idle: 0    # 连接池中的最小空闲连接
    timeout: 1000   # 连接超时时间（毫秒）
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sages?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.sages.app: debug
    com.sages.app.mapper: trace
mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sages.app.mapper
#mapper:
#  mappers:
#    - tk.mybatis.mapper.common.Mapper
#  not-empty: true
#  style: camelhump
#  wrap-keyword: "`{0}`"
#  safe-delete: true
#  safe-update: true
#  identity: MYSQL
pagehelper:
  auto-dialect: true
  helper-dialect: mysql
  reasonable: true
  params: count=countSql



constant:
  error-log-stack-number: 3
